name: Sync Destiny manifest to KV store

on:
  push:
  workflow_dispatch:
    inputs:
      shardCount:
        description: "Shard count"
        type: string
        required: true
        default: "10"

jobs:
  check-manifest:
    name: Manifest check
    runs-on: ubuntu-latest

    outputs:
      matrix: ${{ steps.manifest.outputs.matrix }}
      cache-key: ${{ steps.manifest.outputs.cache-key }}

    steps:
      - uses: actions/checkout@v3

      - name: Use Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Install NPM dependencies
        run: npm install --no-audit

      - name: Set required actions environment variables
        uses: actions/github-script@v6
        id: env
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL);
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN);
      - name: Get latest manifest
        id: manifest
        env:
          ACTIONS_CACHE_URL: ${{ env.ACTIONS_CACHE_URL }}
          ACTIONS_RUNTIME_TOKEN: ${{ env.ACTIONS_RUNTIME_TOKEN }}
          BUNGIE_API_KEY: ${{ secrets.BUNGIE_API_KEY }}
          SERVER_URL: ${{ secrets.SERVER_URL }}
          SHARD_COUNT: ${{ inputs.shardCount || '10' }}
        run: node src/downloadManifest.mjs

  sync-manifest:
    name: ${{ matrix.name }}
    needs: check-manifest
    runs-on: ubuntu-latest

    strategy:
      matrix: ${{ fromJSON(needs.check-manifest.outputs.matrix )}}

    env:
      CACHE_PATH: manifest-cache

    steps:
      - uses: actions/checkout@v3

      - name: Use Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Install NPM dependencies
        run: npm install --no-audit

      - name: Restore manifest from cache
        uses: actions/cache@v3
        with:
          path: ${{ env.CACHE_PATH }}
          key: ${{ needs.check-manifest.outputs.cache-key }}

      - name: Sync tables to KV store
        env:
          BUNGIE_API_KEY: ${{ secrets.BUNGIE_API_KEY }}
          SERVER_URL: ${{ secrets.SERVER_URL }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_NAMESPACE_ID: ${{ secrets.CLOUDFLARE_NAMESPACE_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          MANIFEST_TABLES: ${{ matrix.tables }}
        run: node src/syncManifestTable.mjs
